#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

workspace 'MLInputDodger.xcworkspace'

target 'MLInputDodger' do
	project 'MLInputDodger.xcodeproj'
    
	pod 'MLInputDodger', :path => '../MLInputDodger.podspec'
end